### ISSUE TITLE
"minutes ago" not updating

### ISSUE THREAD

**Issue by jbfeutz** [VeryKross/BGBuddy#2]
My display is stuck on 1m ago. I actually built three and all had the same issue.

**Comment by jbfeutz** [comment]
Resolved itself after a few hours

**Comment by VeryKross** [comment]
That's really curious - could have been something of a hiccup from NightScout itself. The reason I say that is because the "minutes ago" text is being received from NightScout. I may need to look into adding some sort of basic logging that could be viewed from BG Buddy's config web page to help diagnose it. Let me know if it happens again.
