### ISSUE TITLE
Problems compiling the sketch

### ISSUE THREAD

**Issue by sergiotome** [VeryKross/BGBuddy#4]
Hi @VeryKross!

First of all let me thank you for the amazing work you have done with this. I bought all the must have components and I'm able to set up a BG monitor for about 5€, which is great. The installation is also very simple given the instructions you provided, and loading the image with the flasher simple and quick. I have my device running already although I'm still figuring out which case to use since I don't have a 3D printer...

Having said that, I'm not a punp user, and therefore a lot of the stuff displayed in the sample screens are useless for me. They are in fact not printed at all when I flashed the firmware. But I'd like to use that space to display some other info that might be relevent in my case, such as the delta for instance, or otherwise make the reading and the arrow a little bigger to occupy the space that becomes empty since I don't have pump info available.

I loadind the ino in Arduino IDE (v2.0.4) and run into a few problems. Let me say that I'm not a C++ developer, but I have done a few things in Arduino already for M5Stack/StickC. I managed to load all the required libraries and was able to connect to the device successfully, but when I try to verify the code, I get a bunch of errors.

The first error I got is this one:
![image](https://user-images.githubusercontent.com/16870246/225316140-a211536b-4cb0-42b4-b09e-1bca4d80efbc.png)

After some research looks like in the latest versions of C++ you cannot assign a string to a Char pointer. I fixed it by delaring the directarr variable as a string instead.

Then I also get this other error, and here is where I'm stuck and I don't know how to continue:

![image](https://user-images.githubusercontent.com/16870246/225316484-1595348d-e01a-40f1-b1a6-05a5c6b5ae09.png)

If you could help me getting that fixed it would be great. The changes I want to make are relatively simple, although if we want to make this available for everyone we could also add a property in the config page to determine whether the user is a pump user (and display certain info) or not (and display other).

Please let me know if you can help with this.

Thanks,
Sergio

**Comment by VeryKross** [comment]
Hi Sergio,

Great to hear from you and thanks for the kind words! It looks like the
v2.0.4 version of the Arduino IDE introduced that char* issue; once I
upgraded my IDE from 2.0.3 I was able to reproduce the build error. I ended
up fixing it a bit differently since I was only using those characters as a
flag anyway (part of an older code change) and so I've just done away with
them and am using a bool flag which, really, is cleaner anyway.

The second output screen you're showing isn't actually an error - it's just
part of the IDE's build info. However, I *am* seeing another issue while
running - it seems that the upgrade also broke something related to how it
interprets the data coming back from Nightscout and so have to dig into
that later today and hopefully get a fix in place shortly and update GitHub
with the changes.

That said, your situation is definitely not part of the current use case;
the little beastie does current assume there's a pump involved. However,
I'm more than happy to add a non-pump option and make that configurable
since I doubt very much you're the only one running like that 😀

If you're willing to share a link to your Nightscout site, I can pull down
the JSON data that it's producing so I can better understand what our
options are. From there, you can let me know what bits of info would be
most valuable and I'll work up an alternate display layout for the
"pumpless" mode. It should be easy enough to send you a couple test images
along the way so you can easily flash your device and test.

Once it's Sergio Approved, we'll call that v1.5, update the docs, and post
the revised edition.

Ken

**Comment by sergiotome** [comment]
Hi @VeryKross,

Thanks for the quick response. I figured earlier today that those red messages were not in fact an error, so I managed to compile and run the sketch. I'm running into other problems now though. If I flash the binary that you have [here](https://github.com/VeryKross/BGBuddy/tree/main/v1/bin) everything works nicely. I can see in the serial monitor how the device connects to nightscout every minute with a successfull processing of the response. However, if I just upload from Arduino IDE the sketch from [here](https://github.com/VeryKross/BGBuddy/tree/main/v1/src) the api connection doesn't work most of the times (although eventually it does from time to time. Here is a screenshot of my logs:

![image](https://user-images.githubusercontent.com/16870246/225400608-117b9ba7-773a-4f12-b4d5-ea56a9b5481b.png)


Something I noticed is that the Sketch is labeled as version 1, while the binary is labeled as version 1.1. Is there any change that we are missing in the source code on the repo?

**Comment by sergiotome** [comment]
By the way, here is a sample JSON response from my nightscout:

```
{
	"bgnow": {
		"mean": 102,
		"last": 102,
		"mills": 1678885205604,
		"sgvs": [
			{
				"_id": "wLceE5oEDxjLBsAZkQoGB4KT",
				"mgdl": 102,
				"mills": 1678885205604,
				"device": "ABBOTT3MH0616TM7W",
				"direction": "Flat",
				"filtered": 102000,
				"unfiltered": 102000,
				"noise": 1,
				"type": "sgv",
				"scaled": 102
			}
		]
	},
	"pump": {
		"data": {
			"level": -3,
			"clock": null,
			"reservoir": null,
			"reservoir_display_override": null,
			"reservoir_level_override": null,
			"extended": null,
			"device": {
				"label": "Device"
			},
			"title": "Pump Status"
		}
	}
}
```

And here how the screen looks like for people that has no pump data

![image](https://user-images.githubusercontent.com/16870246/225401936-32067a8a-ec2f-4bda-96eb-d375833251ba.png)


I see two options here for people with no pump. We can either make the reading and the arrow bigger (making it a 3 size instead of 2) and moving it down in the screen, or complete the bottom part of the screen with something like the delta, which would require adding also the delta property to the api call

**Comment by VeryKross** [comment]
I've diagnosed it down to the API call itself is failing (not the JSON deserialization) but I'm not sure yet what in the Arduino update has broken it; more research this evening. We probably can't make the text any larger - I'll try it but it isn't very granular. I like the idea of finding some other useful data to display and certainly could add the delta to it.

**Comment by VeryKross** [comment]
> Hi @VeryKross,
> 
> Thanks for the quick response. I figured earlier today that those red messages were not in fact an error, so I managed to compile and run the sketch. I'm running into other problems now though. If I flash the binary that you have [here](https://github.com/VeryKross/BGBuddy/tree/main/v1/bin) everything works nicely. I can see in the serial monitor how the device connects to nightscout every minute with a successfull processing of the response. However, if I just upload from Arduino IDE the sketch from [here](https://github.com/VeryKross/BGBuddy/tree/main/v1/src) the api connection doesn't work most of the times (although eventually it does from time to time. Here is a screenshot of my logs:
> 
> ![image](https://user-images.githubusercontent.com/16870246/225400608-117b9ba7-773a-4f12-b4d5-ea56a9b5481b.png)
> 
> Something I noticed is that the Sketch is labeled as version 1, while the binary is labeled as version 1.1. Is there any change that we are missing in the source code on the repo?

The "major version" is v1 but within the sketch, near the top, is a variable that holds the actual version (1.1) that is displayed. The major version or "series" will stay at v1 until v2 launches (that's where the warning and alerts will be added).

**Comment by VeryKross** [comment]
Okay, so the issue is not with BGBuddy at all - it's the new version of the esp8266 board package (currently v3.1.1). There are several issues files on the 3.1.x version dealing with various http issues. It may be possible to work around them but the current "fix" is simply to revert the package back to version 3.0.2 (the latest pre-3.1.x version). One you do that, the Get functions correctly again.

**Comment by VeryKross** [comment]
Also, once I push the next update, it will automatically display the Delta at the bottom if there is no pump data available.
![20230316_013713204_iOS](https://user-images.githubusercontent.com/11561147/225487515-6174aedd-0c80-4f0d-9338-e12061c8ba23.jpg)

**Comment by sergiotome** [comment]
Ohh, nice. I will still play around with the code today if I have time, but looks like you already made the changes I was interested on. This is a great contribution to the community. Will only reach out again if I discover a bug, find something new that could be interesting to others, or to show you how my final case and set up ends up being :) thanks buddy

**Comment by VeryKross** [comment]
@sergiotome I've updated the source to v1.2 and removed the v1.1 binary - we're now officially at v1.2 across the board.
