### ISSUE TITLE
which ESP8266 card to choose ?

### ISSUE THREAD

**Issue by Odroid13** [VeryKross/BGBuddy#7]
I wanted to thank you for your project, I find it extraordinary, I will use it for sport, when I cycle for several kilometers. A visualization on my handlebars would be great ^^

After reading the PDF file, I think I can do the same thing ^^

On the aliexpress website there are 2 ESP8266 references: V3 Nodemcu-CH340 and V2 Nodemcu-CP2102

Can you confirm which one is correct?

https://fr.aliexpress.com/item/1005006861024522.html?spm=a2g0o.cart.0.0.c028378drLUoye&mp=1&gatewayAdapt=glo2fra4itemAdapt

Also tell me if it will work with any Nightscout website? I use Render.

Also tell me if there is a possibility of lowering the screen brightness to save battery?

The glucose check is done every how many minutes please?

Thank you so much

**Comment by VeryKross** [comment]
That device should work fine and of course you'll also need to get the screen and wire them up. For your purposes, you might want to consider this device which has a built-in LCD screen and basically works "out of the box" without any wiring. I have a separate binary download for this one since the pins they use to connect their display are non-standard.
https://fr.aliexpress.com/item/1005006011203112.html

I don't currently have any way to dim the LCD - it would be possible with a little extra programming.

BGBuddy should work fine for any Nightscout site running version 15.0.2 or above. The software does make some assumptions about how the site is being used though and in particular it expects that you have an insulin delivery and monitoring kit connected to the site using Loop.  It may be possible to modify BGBuddy to work with other configurations but that's been its focus up to now.

**Comment by Odroid13** [comment]
I have the same card with USB-C port. The first time I used the card, the screen lit up and it said "Hello World"

https://www.aliexpress.us/item/3256805824888360.html?gatewayAdapt=fra2usa4itemAdapt

I flashed the card with the BG Buddy file “BGBuddy_v1.2_IdeaSpark.bin”. The flash is working well, I can observe in the Esphome Flasher console: the file is installed correctly and I can see in the Bg Buddy wifi networks and I can even access the 10.10.10.10 web page. But why do I have no image feedback on the screen of the ESP8266 card?

Card ESP8266 information:

![Capture d'écran 2024-05-19 082034](https://github.com/VeryKross/BGBuddy/assets/97029183/dbef6982-a21f-4b9d-80ba-4031ee9f0292)

Thanks

**Comment by VeryKross** [comment]
Yes, unfortunately there aren't any standards out there that I could find. Most project examples I looked at used D1 and D2 for clock and data respectively, but when I got the IdeaSpark card it was following its own "standard". Now I see that your variation of that same design is different again.

This gets a bit trickier as more features are enabled, for example BG Buddy also supports having an external status LED that flashes the same way as the built-in blue LED on the board that is driven by pin D6. There's even a planned warning/alert feature that is currently wired to D5 for an LED and D4 for a buzzer. Unfortunately, any of those could overlap the "standard" from one of these chip+screen packages (like your GPIO12 and GPIO14 do).

I had hoped that by supporting a couple of very specific boards I could make it easier on people since the vast majority of BG Buddy users are not at all technical. What might make sense would be to add an "advanced" settings section to the BG Buddy setup page so you could remap these values if you have the information and experience to do it. That doesn't preclude adding addition pre-configured builds (like the one for IdeaSpark) but it would certainly help situations like yours.

In thinking about your specific usage, I was also wondering if it might make more sense to use an e-Ink display instead of OLED. That would use far less battery power and if BG Buddy was configured to check for new data on a slower interval, maybe every 5 or 10 minutes, that would further reduce battery by not using the WiFi. I've not tried it with an e-Ink display but it would likely require some small changes. The timing change I was considering adding anyway since for some users, checking every minute for data that only updates on Nighscout every 5 minutes doesn't add much value other than refreshing the clock.

**Comment by VeryKross** [comment]
I'm getting ready to release a version 1.3 later today (improvements to connectivity and Nightscout API usage). When I do, I'll create two versions of the IdeaSpark bin file so you'll be able to give it a try. It will take much longer for me to make it all configurable but it's "on the list" :)

**Comment by Odroid13** [comment]
> I'm getting ready to release a version 1.3 later today (improvements to connectivity and Nightscout API usage). When I do, I'll create two versions of the IdeaSpark bin file so you'll be able to give it a try. It will take much longer for me to make it all configurable but it's "on the list" :)

Really a good idea for configuration from the WEB page. I'm looking forward to this update, thank you very much

**Comment by VeryKross** [comment]
Try this build and let me know if it works on your device.
[Uploading BGBuddy_v1.3_IdeaSpark-SDA14.zip…]()

**Comment by VeryKross** [comment]
I wanted to let you know that I've now updated all of the binaries to v1.3 here on the site, including two variations for IdeaSpark. Thanks for the feedback and let me know if you have any other issues.

**Comment by Odroid13** [comment]
Hi, I'm surprised at how quickly you updated.  Everything works, thank you.
